databases:
  - name: jedi_path_quizventure
    plan: free
    databaseName: jedi_path_quizventure
    user: jedi_path_quizventure_user

services:
  - type: web
    plan: free
    name: jedi_path_quizventure
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend_main.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jedi_path_quizventure
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4