# Generated by Django 4.2.13 on 2024-05-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='characters/')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='frontend.planet')),
            ],
        ),
    ]
